### ISSUE TITLE
Unable to mix JSONKeyPath with Enum annotations

### ISSUE THREAD

**Issue by AlainMullerNiji** [NijiDigital/dbgenerator#15]
If I want to use an enum and have a _SerializedName_ annotation for it's original field, it won't work : 
`/.../dbgenerator/lib/dbgenerator/utils/raise.rb:20:in `error': ! The attribute "authType" from "Customer" is wrongly annotated enum - please fix it (RuntimeError)`

Having authType as Integer 16 and associated to keys : 
- JSONKeyPath : auth_type
- enumType : AuthType
- enumValues : guest,registered

**Comment by AliSoftware** [comment]
Does this crash occurs only when you generate RealmJava code or also when generating RealmSwift code ?

**Comment by AlainMullerNiji** [comment]
Good question, I generated both of it ^^"

This crash happens on both Swift/Java generation

**Comment by AlainMullerNiji** [comment]
```
/Users/amuller/dev/tools/dbgenerator/lib/dbgenerator/utils/raise.rb:20:in `error': ! The attribute "authType" from "Customer" is wrongly annotated enum - please fix it (RuntimeError)
	from /Users/amuller/dev/tools/dbgenerator/lib/dbgenerator/xcdatamodel/parser/attribute.rb:91:in `search_for_error'
	from /Users/amuller/dev/tools/dbgenerator/lib/dbgenerator/xcdatamodel/parser/attribute.rb:47:in `initialize'
	from /Users/amuller/dev/tools/dbgenerator/lib/dbgenerator/xcdatamodel/parser/entity.rb:217:in `new'
	from /Users/amuller/dev/tools/dbgenerator/lib/dbgenerator/xcdatamodel/parser/entity.rb:217:in `block in load_attributes'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/gems/2.0.0/gems/nokogiri-1.5.6/lib/nokogiri/xml/node_set.rb:239:in `block in each'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/gems/2.0.0/gems/nokogiri-1.5.6/lib/nokogiri/xml/node_set.rb:238:in `upto'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/gems/2.0.0/gems/nokogiri-1.5.6/lib/nokogiri/xml/node_set.rb:238:in `each'
	from /Users/amuller/dev/tools/dbgenerator/lib/dbgenerator/xcdatamodel/parser/entity.rb:216:in `load_attributes'
	from /Users/amuller/dev/tools/dbgenerator/lib/dbgenerator/xcdatamodel/parser/entity.rb:211:in `load_entity'
	from /Users/amuller/dev/tools/dbgenerator/lib/dbgenerator/xcdatamodel/parser/entity.rb:39:in `initialize'
	from /Users/amuller/dev/tools/dbgenerator/lib/dbgenerator/xcdatamodel/parser/xcdatamodel.rb:52:in `new'
	from /Users/amuller/dev/tools/dbgenerator/lib/dbgenerator/xcdatamodel/parser/xcdatamodel.rb:52:in `block in load_entities'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/gems/2.0.0/gems/nokogiri-1.5.6/lib/nokogiri/xml/node_set.rb:239:in `block in each'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/gems/2.0.0/gems/nokogiri-1.5.6/lib/nokogiri/xml/node_set.rb:238:in `upto'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/gems/2.0.0/gems/nokogiri-1.5.6/lib/nokogiri/xml/node_set.rb:238:in `each'
	from /Users/amuller/dev/tools/dbgenerator/lib/dbgenerator/xcdatamodel/parser/xcdatamodel.rb:51:in `load_entities'
	from /Users/amuller/dev/tools/dbgenerator/lib/dbgenerator/xcdatamodel/parser/xcdatamodel.rb:37:in `initialize'
	from /Users/amuller/dev/tools/dbgenerator/bin/dbgenerator:99:in `new'
	from /Users/amuller/dev/tools/dbgenerator/bin/dbgenerator:99:in `<main>'
```

**Comment by AliSoftware** [comment]
Ok so after reading the code and the xcdatamodel, the error is actually normal. The problem is more error message that is not really clear and should be improved.

The problem is that when you declare the `enumValues` for a type that also has `JSONKeyPath`, **you must also declare the `JSONValues` annotation** — with the same number of values — to tell the mapping between the values expected in the JSON and the enum case names in your code.
Because the list of values returned by the WebService might not match the names you want in your code (e.g. `"M,F"` returned by the JSON but you want `MALE` and `FEMALE` names for your enum cases in your code)

I'll add a commit on master to improve the error message and make it more understandable.

**Comment by AliSoftware** [comment]
Documentation & error message improved by commit e6e5d1bdd11f0ccd49b2a0b9ddb4a16625f5501f on `master` 👍
